name: high_term
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.3.9
  xterm: ^4.0.0
  screen_retriever: ^0.1.9
  cupertino_icons: ^1.0.6
  flutter_acrylic: ^1.1.0
  macos_ui: ^2.0.7
  flutter_pty: ^0.4.0
  hemend:
    git:
      url: https://github.com/FMotalleb/flutter_hemend_core.git
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  path_provider: ^2.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  moti_lints: ^1.1.3

flutter:
  uses-material-design: true
